# Generated by Django 4.2.7 on 2023-12-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_bid_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bids_placed",
            field=models.ManyToManyField(
                blank=True, related_name="bidders", to="auctions.bid"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="listings_placed",
            field=models.ManyToManyField(
                blank=True, related_name="seller_listings", to="auctions.listing"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to="auctions.listing"
            ),
        ),
    ]
